# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute the app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

pool:
  vmImage: 'macOS 10.13'

steps:
- task: Xcode@5
  inputs:
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcodeVersion: '10' # Options: 8, 9, default, specifyPath
- task: XcodePackageiOS@0
  inputs:
    appName: 'name.app' 
    ipaName: 'name.ipa' 
    provisioningProfile: 
    sdk: 'iphoneos' 
    appPath: '$(SDK)/$(Configuration)/build.sym/$(Configuration)-$(SDK)' 
    ipaPath: '$(SDK)/$(Configuration)/build.sym/$(Configuration)-$(SDK)/output' 
